services:
  - name: web
    buildCommand: npm ci
    startCommand: npm run start
    env:
      - key: NODE_VERSION
        value: 22.13.1
      - key: MONGODB_URI
        fromEnv: MONGODB_URI
    routes:
      - url: /*