services:
  - name: web 
    build: ./ 
    env:
      - key: NODE_VERSION 
        value: 16.20.0
      - key: MONGODB_URI 
        fromEnv: MONGODB_URI 
    routes:
      - url: /* 
    buildCommand: npm install
    startCommand: npm run start